services:
  app:
    build: 
      context: ../../
      dockerfile: build/package/Dockerfile
    entrypoint: sh ./scripts/docker-entrypoint.sh
    container_name: go_grpc
    working_dir: /app
    volumes:
      - ../../:/app
    ports:
      - 8080:8080
