apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: go-server
        image: kevin/19-deploy-k8s:latest
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"

        # startup probe - run when the container starts
        startupProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 10

        # readiness probe - run when the container is ready to check if it is good to receive traffic
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 2
          timeoutSeconds: 5

        # liveness probe - run when the container is running to check if it is still alive and restart if not
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
          successThreshold: 1

        ports:
        - containerPort: 8080