services:
  app:
    build: 
      context: ../../
      dockerfile: build/package/Dockerfile
    container_name: go_api
    working_dir: /app
    volumes:
      - ../../:/app
    ports:
      - 3000:3000
