POST http://localhost:3000/product HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtAZy5jIiwiZXhwIjoxNzE5NjAxNzgzLCJzdWIiOiIwZTI0YjIyOC03Mzc5LTQxMDItYTZlOS1mODRkMmM5OTUwY2UifQ._3KGV8Bmt49LFuZd4d-PNz5CMX6Lo1y1zEhjJ8UeDIw

{
    "name": "Product 1",
    "price": 100
}

###

GET http://localhost:3000/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtAZy5jIiwiZXhwIjoxNzE5NjAxNzgzLCJzdWIiOiIwZTI0YjIyOC03Mzc5LTQxMDItYTZlOS1mODRkMmM5OTUwY2UifQ._3KGV8Bmt49LFuZd4d-PNz5CMX6Lo1y1zEhjJ8UeDIw

###

GET http://localhost:3000/product/e798b9f3-340e-42e8-acf6-a9aac55dff35 HTTP/1.1

###

PUT http://localhost:3000/product/e798b9f3-340e-42e8-acf6-a9aac55dff35 HTTP/1.1
Content-Type: application/json

{
    "name": "changed",
    "price": 897320,
    "created_at": "2024-06-27T20:30:15.161109201Z"
}

###

DELETE http://localhost:3000/product/e798b9f3-340e-42e8-acf6-a9aac55dff35 HTTP/1.1
